
spring:
  application:
    name: config-server
  cloud:
    config:
      #\u914D\u7F6E\u4ED3\u5E93\u5206\u652F
      label: master
      server:
        git:
          #\u914D\u7F6Egit\u4ED3\u5E93\u5730\u5740
          uri: https://gitee.com/Soft_Vigorous/spcloud/
#          uri: https://github.com/forezp/SpringcloudConfig/
#          uri: https://github.com/vigorous/spcloud/
          #\u914D\u7F6E\u4ED3\u5E93\u8DEF\u5F84
          search-paths: docs
          #\u7528\u6237\u540D
          username:
          #\u5BC6\u7801
          password:
#\u670D\u52A1\u7AEF\u53E3
server:
  port: 8888