#说明服务注册中心的url
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#服务端口
server:
  port: 8769

#
spring:
  application:
    name: spcloud-service-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: spcloud-service-ribbon
    api-b:
      path: /api-b/**
      serviceId: spcloud-service-feign

